spring:
  profiles: dev
  application:
    name: TRAINER-WORKLOAD-SERVICE
server:
  port: 8081
auth:
  bearer:
    token: 'myBearerToken2'
secret-key: 'mySecretKey1234567890mySecretKey1234567890mySecretKey1234567890mySecretKey1234567890'
audience-type: 'service'
mq:
  password: 'admin'
  username: 'admin'
  url: 'tcp://localhost:61616'
  converter:
    type-id-property-name: '_type'
  factory:
    concurrency: '1-1'
  queue:
    name:
      workload: 'trainer-workload-queue'
      dlq: 'ActiveMQ.DLQ'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost

---

spring:
  profiles: test
  application:
    name: TRAINER-WORKLOAD-SERVICE
server:
  port: 8091
auth:
  bearer:
    token: 'myBearerToken2'
secret-key: 'mySecretKey1234567890mySecretKey1234567890mySecretKey1234567890mySecretKey1234567890'
audience-type: 'service'
mq:
  password: 'admin'
  username: 'admin'
  url: 'tcp://localhost:61616'
  converter:
    type-id-property-name: '_type'
  factory:
    concurrency: '1-1'
  queue:
    name:
      workload: 'trainer-workload-queue'
      dlq: 'ActiveMQ.DLQ'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost

---

spring:
  profiles: prod
  application:
    name: TRAINER-WORKLOAD-SERVICE
server:
  port: 8083
auth:
  bearer:
    token: 'myBearerToken2'
secret-key: 'mySecretKey1234567890mySecretKey1234567890mySecretKey1234567890mySecretKey1234567890'
audience-type: 'service'
mq:
  password: 'admin'
  username: 'admin'
  url: 'tcp://localhost:61616'
  converter:
    type-id-property-name: '_type'
  factory:
    concurrency: '1-1'
  queue:
    name:
      workload: 'trainer-workload-queue'
      dlq: 'ActiveMQ.DLQ'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost