spring:
  profiles: dev
  application:
    name: TRAINER-WORKLOAD-SERVICE
  data:
    mongodb:
      auto-index-creation: true
      host: mongodb
      port: 27017
      database: workload
      username: ${MONGO_USER}
      password: ${MONGO_PASSWORD}
      authentication-database: admin
server:
  port: 8081
auth:
  bearer:
    token: 'myBearerToken2'
secret-key: 'mySecretKey1234567890mySecretKey1234567890mySecretKey1234567890mySecretKey1234567890'
audience-type: 'service'
mq:
  password: ${ACTIVEMQ_ADMIN_PASSWORD}
  username: ${ACTIVEMQ_ADMIN_LOGIN}
  url: 'tcp://activemq:61616'
  converter:
    type-id-property-name: '_type'
  factory:
    concurrency: '1-1'
  queue:
    name:
      workload: 'trainer-workload-queue'
      dlq: 'ActiveMQ.DLQ'
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true

---

spring:
  profiles: test
  application:
    name: TRAINER-WORKLOAD-SERVICE
  data:
    mongodb:
      auto-index-creation: true
      host: localhost
      port: 27019
      username: admin
      password: admin
      database: workload
      authentication-database: admin

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
  port: 8091
auth:
  bearer:
    token: 'myBearerToken2'
secret-key: 'mySecretKey1234567890mySecretKey1234567890mySecretKey1234567890mySecretKey1234567890'
audience-type: 'service'
mq:
  password: 'admin'
  username: 'admin'
  url: 'tcp://localhost:8199'
  converter:
    type-id-property-name: '_type'
  factory:
    concurrency: '1-1'
  queue:
    name:
      workload: 'trainer-workload-queue'
      dlq: 'ActiveMQ.DLQ'
eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost


