spring:
  profiles: dev
  application:
    name: TRAINER-WORKLOAD-SERVICE
server:
  port: 8081
auth:
  bearer:
    token: 'myBearerToken2'
secret-key: 'mySecretKey1234567890mySecretKey1234567890mySecretKey1234567890mySecretKey1234567890'
audience-type: 'service'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost

---

spring:
  profiles: test
server:
  port: 8000
auth:
  bearer:
    token: 'myBearerToken'
secret-key: 'mySecretKey1234567890mySecretKey1234567890mySecretKey1234567890mySecretKey1234567890'

---

spring:
  profiles: prod
server:
  port: 8082
auth:
  bearer:
    token: 'myBearerToken'
secret-key: 'mySecretKey1234567890mySecretKey1234567890mySecretKey1234567890mySecretKey1234567890'